### ISSUE TITLE
How to handle backpresses() only in specific states 

### ISSUE THREAD

**Issue by nourbt** [eliekarouz/FeedbackTree#2]
I want to be able to click back only when the state in sign in mode. How to handle this in the layout?

**Comment by eliekarouz** [comment]
@nourbt 
You can use a `react` feedback loop to solve your problem...
```kotlin
fun backPressesFeedback() = react<State, Unit, Bool>(
    query = { state -> someConditionThatReturnsUnitWhenYouEnableBackPresses },
    effects = {
           view.backPresses().map { Event.PressedBack }
    }
)
```
When the `query` returns `null`, the back press is not handled by the view anymore...

**Comment by eliekarouz** [comment]
Actually there is an issue, the code doesn't unregister from the back presses when the `effect` is disposed. I will fix it soon...

**Comment by eliekarouz** [comment]
Duplicates #1
